/-
VARIANT 5 -- is the SECOND SHEET of the double cover necessary?

This is the deepest of the variants, because the paper argues the point in prose
and never proves it.  Section 4:

  "The classical reduction fails at its final step.  In basic modal logic, a
   pointed local countermodel is restricted to the submodel generated by its
   point. […] This invariance argument is unavailable here.  An element variable
   may be assigned outside the generated part, and ∃x quantifies over that
   assignment."

and later:

  "Removing element variables and ∃ identifies the new content of this
   construction. […] The set C is already a countermodel, Lemma 11 is
   unnecessary, and one may take N := C."

So the paper says: with `∃` present, the generated submodel `C` alone does NOT
work, and that is precisely why Definition 10 doubles it.  It gives no
counterexample.

This file takes the single-sheet reading -- `N := C`, the submodel induced on a
backward-closed `C` -- and asks whether Corollary 12 survives it.  A refutation
would mechanize the paper's own justification for the double cover.
-/
import MatchingLogic.Composite

namespace MatchingLogic
namespace VariantSingleSheet

variable {S : Signature} {Var : Type} [DecidableEq Var]

/-- The submodel induced on `C`: one sheet, no phantom. -/
def single (M : Model S) (C : Set M.carrier) (hne : C.Nonempty) : Model S where
  carrier := C
  nonempty := ⟨⟨hne.choose, hne.choose_spec⟩⟩
  interp := fun σ A => {u | (u : M.carrier) ∈ M.interp σ (fun j => ((A j : M.carrier)))}

/-- Corollary 12, stated for the single sheet: `N ⊨ ψ` iff `C ⊆ ⟦ψ⟧_M`, for
closed `ψ`. -/
def V5Claim : Prop :=
  ∀ (S : Signature) (Var : Type) (_ : DecidableEq Var) (M : Model S)
    (C : Set M.carrier) (_ : M.BackwardClosed C) (hne : C.Nonempty)
    (star : M.carrier) (_ : star ∉ C)
    (ψ : Pattern S Var) (_ : Closed ψ) (ρ : Var → M.carrier),
      (single M C hne).Sat ψ ↔ C ⊆ M.denote ρ ψ

theorem v5_holds : V5Claim := by sorry

/-!
## Countermodel

Take the empty signature, the two-element carrier `Bool`, and the backward-closed
singleton `C = {false}`.  The closed pattern `∀x. x` is total in the induced
single-sheet model, because its carrier has just one element.  In the ambient
model it has empty denotation: the `x := true` instance excludes `false` (and
the `x := false` instance excludes `true`).
-/

/-- The empty signature. -/
abbrev ssSig : Signature where
  Sym := Empty
  arity := fun σ => Empty.elim σ

/-- A two-element model; the interpretation is vacuous because there are no symbols. -/
abbrev ssModel : Model ssSig where
  carrier := Bool
  nonempty := ⟨false⟩
  interp := fun σ _ => Empty.elim σ

/-- The singleton generated part. -/
abbrev ssC : Set ssModel.carrier := {false}

theorem ssC_nonempty : ssC.Nonempty := ⟨false, rfl⟩

theorem ssC_backwardClosed : ssModel.BackwardClosed ssC := by
  rintro u hu v ⟨σ, a, i, hinterp, rfl⟩
  exact Empty.elim σ

theorem ssStar : (true : ssModel.carrier) ∉ ssC := by simp

/-- `∀x. x`, which is total exactly when the carrier is a singleton. -/
abbrev ssPat : Pattern ssSig Unit := Pattern.al () (.var ())

theorem ssPat_closed : Closed ssPat := by
  simp [ssPat, Pattern.al, Pattern.nt, Closed]

theorem v5_fails : ¬ V5Claim := by
  intro h
  let ρ : Unit → ssModel.carrier := fun _ => false
  have hiff := h ssSig Unit inferInstance ssModel ssC ssC_backwardClosed
    ssC_nonempty true ssStar ssPat ssPat_closed ρ
  have hsingle : ∀ a b : ssC, a = b := by
    intro a b
    apply Subtype.ext
    simpa using a.property.trans b.property.symm
  have hleft : (single ssModel ssC ssC_nonempty).Sat ssPat := by
    intro ν
    apply Set.eq_univ_iff_forall.mpr
    intro p
    rw [denote_al]
    simp only [Set.mem_iInter, denote_var, Set.mem_singleton_iff]
    intro a
    exact hsingle p (Function.update ν () a ())
  have hright : ¬ ssC ⊆ ssModel.denote ρ ssPat := by
    intro hsub
    have hfalse := hsub (show false ∈ ssC by rfl)
    rw [denote_al] at hfalse
    have htrue := Set.mem_iInter.mp hfalse true
    simp at htrue
  exact hright (hiff.mp hleft)

/-- **Control.** The paper's actual double cover has two carrier elements and
therefore does not satisfy `∀x. x`, agreeing with the ambient right-hand side.
This is exactly the extra witness unavailable in the single sheet. -/
theorem ss_real_cover_not_sat :
    ¬ (cover ssModel ssC ssC_nonempty).Sat ssPat := by
  intro hsat
  let ρ : Unit → ssModel.carrier := fun _ => false
  have hsub := (cover_sat_iff ssModel ssC ssC_backwardClosed ssC_nonempty
    true ssStar ssPat_closed ρ).mp hsat
  have hfalse := hsub (show false ∈ ssC by rfl)
  rw [denote_al] at hfalse
  have htrue := Set.mem_iInter.mp hfalse true
  simp at htrue

end VariantSingleSheet
end MatchingLogic

#print axioms MatchingLogic.VariantSingleSheet.v5_fails
