-- Entry-point (iii), wave 1: total source-style substitution over raw Nat names.
import MatchingLogic.EntryIII.CaptureAvoiding

#check @MatchingLogic.Pattern.substVar_self
#check @MatchingLogic.Pattern.captureFree_self
#check @MatchingLogic.Provable.ex_mono
#check @MatchingLogic.Provable.imp_mono
#check @MatchingLogic.Provable.app_mono
#print MatchingLogic.Pattern.complexity
#check @MatchingLogic.Pattern.complexity_substVar
#print MatchingLogic.Pattern.AlphaEq
#check @MatchingLogic.Pattern.AlphaEq.refl
#check @MatchingLogic.Pattern.AlphaEq.symm
#check @MatchingLogic.Pattern.AlphaEq.trans
#check @MatchingLogic.Pattern.AlphaEq.imp
#check @MatchingLogic.Pattern.AlphaEq.app
#check @MatchingLogic.Pattern.AlphaEq.ex
#check @MatchingLogic.Pattern.AlphaEq.alphaEx
#check @MatchingLogic.Pattern.AlphaEq.denote_eq
#print MatchingLogic.Pattern.AvoidsBinder
#print MatchingLogic.Pattern.avoidBinder
#check @MatchingLogic.Pattern.AvoidsBinder.substVar
#check @MatchingLogic.Pattern.avoidBinder_avoids
#check @MatchingLogic.Pattern.AvoidsBinder.captureFree
#check @MatchingLogic.Pattern.avoidBinder_alphaEq
#check @MatchingLogic.Pattern.avoidBinder_eq_self_of_not_mem_allVars
#print MatchingLogic.Pattern.captureAvoidingSubst
#print MatchingLogic.Pattern.IsCaptureAvoidingSubst
#check @MatchingLogic.Pattern.captureAvoidingSubst_spec
#check @MatchingLogic.Pattern.exists_isCaptureAvoidingSubst
#check @MatchingLogic.Pattern.captureAvoidingSubst_eq_substVar_of_fresh
#check @MatchingLogic.Pattern.complexity_captureAvoidingSubst
#check @MatchingLogic.Pattern.IsCaptureAvoidingSubst.complexity_eq
#check @MatchingLogic.Model.denote_substVar_of_captureFree
#check @MatchingLogic.Model.denote_captureAvoidingSubst
#check @MatchingLogic.Pattern.IsCaptureAvoidingSubst.denote
#check @MatchingLogic.Provable.captureAvoidingExQuant
#check @MatchingLogic.Pattern.IsCaptureAvoidingSubst.exQuant
