#!/usr/bin/env bash
set -uo pipefail
cd "$(dirname "$0")/.."
{ echo "# Every certified result. Generated by scripts/gen-required.sh."
  echo "# The manifest gate requires all of these to remain certified, so a name"
  echo "# cannot be quietly dropped and its theorem then left unproved. An audit"
  echo "# removed 38 names while an earlier, partial required-list still passed."
  grep -vE '^#|^$' gate/certified.txt; } > gate/required.txt
echo "gate/required.txt: $(grep -cvE '^#|^$' gate/required.txt) required"
