#!/usr/bin/env bash
# Regenerate gate/pinned.lean.
#
# The pin list is enumerated FROM LEAN'S OWN ENVIRONMENT, not by parsing source.
# Six rounds of review broke earlier versions; two of them broke a hand-written
# list (`Pattern.or`, `Srt3`) and then a regex-derived one whose name pattern
# excluded dots and Greek letters, silently dropping `Model.Sat`, `AppCtx.plug`,
# `Γ3` and others. A coverage check written with the SAME regex reported
# "91 of 91" and was comparing the generator against itself.
#
# Asking the kernel which declarations exist removes that class of omission: the
# list cannot miss a declaration because of how its NAME is spelled.
#
# Round eight found what it could still miss: a KIND. The enumeration accepted
# `defnInfo` and `inductInfo` only, so `axiom localCompleteness : ...` was
# invisible to it -- and to every other gate. Theorems and axioms are enumerated
# here too, and `scripts/audit-axiom-decls.sh` fails outright on an `axiom`.
set -uo pipefail
cd "$(dirname "$0")/.."
export PATH="$HOME/.elan/bin:$PATH"
TD=$(mktemp -d); trap 'rm -rf "$TD"' EXIT
ENUM="$TD/enum.lean"
cat > "$ENUM" <<'LEAN'
import MatchingLogic
open Lean in
run_cmd do
  let env ← getEnv
  let mut ds := #[]
  let mut is := #[]
  let mut ts := #[]
  let mut ax := #[]
  for (n, ci) in env.constants.toList do
    let s := n.toString
    unless s.startsWith "MatchingLogic" do continue
    if n.isInternal then continue
    if (s.splitOn "._").length > 1 then continue
    if s.endsWith ".rec" || s.endsWith ".recOn" || s.endsWith ".casesOn" || s.endsWith ".below"
       || s.endsWith ".brecOn" || s.endsWith ".brecOn.go" || s.endsWith ".ndrec" || s.endsWith ".ibelow"
       || s.endsWith ".binductionOn" || s.endsWith ".noConfusion" || s.endsWith ".noConfusionType"
       || s.endsWith ".sizeOf" || s.endsWith ".injEq" || s.endsWith ".inj" || s.endsWith ".eq_def"
       || s.endsWith ".mk" || s.endsWith ".toCtorIdx" || s.endsWith ".ofNat" || s.endsWith ".elim"
       || s.endsWith ".ctorIdx" || s.endsWith ".ctorElim" || s.endsWith ".ctorElimType" then continue
    match ci with
    | .defnInfo _   => ds := ds.push s
    | .inductInfo _ => is := is.push s
    | .thmInfo _    => ts := ts.push s
    | .axiomInfo _  => ax := ax.push s
    | _ => pure ()
  for x in ds.qsort (· < ·) do IO.println s!"D {x}"
  for x in is.qsort (· < ·) do IO.println s!"I {x}"
  for x in ts.qsort (· < ·) do IO.println s!"T {x}"
  for x in ax.qsort (· < ·) do IO.println s!"A {x}"
LEAN
OUT=$(lake env lean "$ENUM" 2>/dev/null | grep -vE '\.(eq_[0-9]|match_[0-9]|proof_[0-9]|_sunfold|_unsafe_rec|_cstage)')
# The enumeration failing silently would produce an empty, trivially-passing pin
# list. It has to have found something of every kind the library actually has.
n_d=$(printf '%s\n' "$OUT" | grep -c '^D ' || true)
n_i=$(printf '%s\n' "$OUT" | grep -c '^I ' || true)
n_t=$(printf '%s\n' "$OUT" | grep -c '^T ' || true)
if [ "$n_d" -lt 50 ] || [ "$n_i" -lt 5 ] || [ "$n_t" -lt 50 ]; then
  echo "FAIL  enumeration returned $n_d definitions, $n_i types, $n_t theorems; it did not run" >&2
  exit 1
fi
{
  echo "-- GENERATED by scripts/gen-pinned.sh from Lean's environment. Do not edit."
  echo "-- Every definition's body, every type's constructor set, and the type of"
  echo "-- every theorem and axiom the environment holds under \`MatchingLogic\`,"
  echo "-- plus the type of every certified statement. Coverage is not curated."
  echo "import MatchingLogic"
  echo ""
  echo "-- Definition BODIES. A weakened definition changes no type, and a theorem"
  echo "-- above it keeps both its statement and its proof."
  printf '%s\n' "$OUT" | awk '$1=="D"{print "#print " $2}'
  echo ""
  echo "-- CONSTRUCTOR SETS. A rule or syntactic form cannot be added, dropped or"
  echo "-- reshaped without the recursor's type changing."
  printf '%s\n' "$OUT" | awk '$1=="I"{print "#check @" $2 ".rec"}'
  echo ""
  echo "-- Every THEOREM's type, whether or not it is certified. A theorem outside"
  echo "-- gate/certified.txt used to be unpinned; so was an \`axiom\`, which is why"
  echo "-- axioms are enumerated below and rejected by audit-axiom-decls.sh."
  printf '%s\n' "$OUT" | awk '$1=="T"{print "#check @" $2}'
  printf '%s\n' "$OUT" | awk '$1=="A"{print "#check @" $2}'
  echo ""
  echo "-- Every certified statement's TYPE, read from gate/certified.txt. This"
  echo "-- repeats part of the block above on purpose: it also checks that every"
  echo "-- name the manifest claims still exists."
  grep -vE '^#|^$' gate/certified.txt | sed 's/^/#check @/'
} > gate/pinned.lean
echo "gate/pinned.lean: $(grep -c '^#print' gate/pinned.lean) bodies, $(grep -c '^#check @.*\.rec$' gate/pinned.lean) constructor sets, $n_t theorem/axiom types, $(grep -cvE '^#|^$' gate/certified.txt) certified statements"
