#!/usr/bin/env bash
# Regenerate gate/pinned.lean: a #check for every certified name, plus #print for
# the definitions those statements are about. Run this after deliberately
# changing a statement, then re-run scripts/audit-pinned.sh.
set -uo pipefail
cd "$(dirname "$0")/.."
{
  echo "-- GENERATED by scripts/gen-pinned.sh. Do not edit by hand."
  echo "-- Every certified name's TYPE is pinned here, so a certified theorem"
  echo "-- cannot be swapped for an unrelated declaration of the same name."
  echo "import MatchingLogic"
  echo ""
  echo "-- Definition BODIES: a weakened definition changes no type."
  for d in MatchingLogic.Model.app MatchingLogic.Model.denote MatchingLogic.Model.BackwardClosed \
           MatchingLogic.AgreeOn MatchingLogic.coverInterp MatchingLogic.cover MatchingLogic.proj \
           MatchingLogic.FV MatchingLogic.Closed MatchingLogic.Model.Sat MatchingLogic.Model.SatSet \
           MatchingLogic.Model.denoteSet MatchingLogic.LocalCons MatchingLogic.GlobalCons \
           MatchingLogic.Coord MatchingLogic.dia MatchingLogic.box MatchingLogic.boxes \
           MatchingLogic.Model.stepAt MatchingLogic.Model.reachWord MatchingLogic.localize \
           MatchingLogic.substVar MatchingLogic.CaptureFree MatchingLogic.PForm.eval \
           MatchingLogic.PForm.subst MatchingLogic.AppCtx.plug MatchingLogic.conj \
           MatchingLogic.StrongLocalCompleteness MatchingLogic.Soundness \
           MatchingLogic.Sorted.mupdate MatchingLogic.Sorted.msubstVar MatchingLogic.Sorted.MCaptureFree \
           MatchingLogic.Sorted.Feeds; do echo "#print $d"; done
  echo ""
  echo "-- The proof system's CONSTRUCTOR SET."
  echo "#check @MatchingLogic.Provable.rec"
  echo "#check @MatchingLogic.Sorted.MProvable.rec"
  echo ""
  echo "-- Every certified statement's TYPE."
  grep -vE '^#|^$' gate/certified.txt | while read -r n; do echo "#check @$n"; done
} > gate/pinned.lean
echo "gate/pinned.lean regenerated: $(grep -c '^#' gate/pinned.lean) checks"
