#!/usr/bin/env python3
"""Emit gate/pinned.lean by walking the library's own declarations.

Coverage is derived, never curated: if a declaration exists under MatchingLogic/,
it is pinned. That is the only way the gate's reach stops depending on whoever
last edited a list.
"""
import re, pathlib, sys

DECL = re.compile(r'^\s*(?:@\[[^\]]*\]\s*)?(?:private\s+|protected\s+|noncomputable\s+)*'
                  r'(def|abbrev|structure|inductive)\s+([A-Za-z_][A-Za-z0-9_₀-₉\'!?]*)')
NS_OPEN = re.compile(r'^\s*namespace\s+([A-Za-z_][A-Za-z0-9_.]*)')
NS_END = re.compile(r'^\s*end\s+([A-Za-z_][A-Za-z0-9_.]*)\s*$')

defs, types = [], []
for path in sorted(pathlib.Path("MatchingLogic").glob("*.lean")):
    stack = []
    for line in path.read_text().splitlines():
        if line.lstrip().startswith("--"):
            continue
        m = NS_OPEN.match(line)
        if m: stack.append(m.group(1)); continue
        m = NS_END.match(line)
        if m and stack and stack[-1].split(".")[-1] == m.group(1).split(".")[-1]:
            stack.pop(); continue
        m = DECL.match(line)
        if not m: continue
        kind, name = m.groups()
        full = ".".join(stack + [name]) if stack else name
        (defs if kind in ("def", "abbrev") else types).append((full, kind))

seen = set()
print("-- GENERATED by scripts/gen-pinned.sh. Do not edit by hand.")
print("-- Coverage is derived from the source: every def, abbrev, structure and")
print("-- inductive under MatchingLogic/, plus every certified statement's type.")
print("import MatchingLogic")
print()
print("-- Definition BODIES. A weakened definition changes no type, and a theorem")
print("-- above it keeps both its statement and its proof.")
for full, _ in defs:
    if full in seen: continue
    seen.add(full); print(f"#print {full}")
print()
print("-- CONSTRUCTOR SETS. A rule or syntactic form cannot be added, dropped or")
print("-- reshaped without the recursor's type changing.")
for full, kind in types:
    if full in seen: continue
    seen.add(full)
    print(f"#check @{full}.rec" if kind == "inductive" else f"#check @{full}.mk")
print()
print("-- Every certified statement's TYPE.")
for n in pathlib.Path("gate/certified.txt").read_text().splitlines():
    n = n.strip()
    if n and not n.startswith("#"): print(f"#check @{n}")

# NOTE. `private def`s cannot be pinned: Lean mangles their names, so `#print`
# cannot reach them, while a private definition CAN still appear in a public
# statement's type. Rather than exempt them, the library has no private
# definitions -- only private *theorems*, whose bodies are proofs and are checked
# by the kernel anyway. If a `private def` is ever reintroduced, this generator
# will emit an unresolvable `#print` and the pinned gate will fail loudly, which
# is the intended behaviour.
