/-
VARIANT 5 -- is the SECOND SHEET of the double cover necessary?

This is the deepest of the variants, because the paper argues the point in prose
and never proves it.  Section 4:

  "The classical reduction fails at its final step.  In basic modal logic, a
   pointed local countermodel is restricted to the submodel generated by its
   point. […] This invariance argument is unavailable here.  An element variable
   may be assigned outside the generated part, and ∃x quantifies over that
   assignment."

and later:

  "Removing element variables and ∃ identifies the new content of this
   construction. […] The set C is already a countermodel, Lemma 11 is
   unnecessary, and one may take N := C."

So the paper says: with `∃` present, the generated submodel `C` alone does NOT
work, and that is precisely why Definition 10 doubles it.  It gives no
counterexample.

This file takes the single-sheet reading -- `N := C`, the submodel induced on a
backward-closed `C` -- and asks whether Corollary 12 survives it.  A refutation
would mechanize the paper's own justification for the double cover.
-/
import MatchingLogic.Composite

namespace MatchingLogic
namespace VariantSingleSheet

variable {S : Signature} {Var : Type} [DecidableEq Var]

/-- The submodel induced on `C`: one sheet, no phantom. -/
def single (M : Model S) (C : Set M.carrier) (hne : C.Nonempty) : Model S where
  carrier := C
  nonempty := ⟨⟨hne.choose, hne.choose_spec⟩⟩
  interp := fun σ A => {u | (u : M.carrier) ∈ M.interp σ (fun j => ((A j : M.carrier)))}

/-- Corollary 12, stated for the single sheet: `N ⊨ ψ` iff `C ⊆ ⟦ψ⟧_M`, for
closed `ψ`. -/
def V5Claim : Prop :=
  ∀ (S : Signature) (Var : Type) (_ : DecidableEq Var) (M : Model S)
    (C : Set M.carrier) (_ : M.BackwardClosed C) (hne : C.Nonempty)
    (star : M.carrier) (_ : star ∉ C)
    (ψ : Pattern S Var) (_ : Closed ψ) (ρ : Var → M.carrier),
      (single M C hne).Sat ψ ↔ C ⊆ M.denote ρ ψ

/-! ### Refutation

The single-sheet reading fails, and it fails exactly where Section 4 says it
must: at `∃`.  A closed pattern can say "the carrier has at most one element",
and shrinking `M` to the submodel on `C` changes the answer.

Data (empty signature, so backward closure is free and no symbol distracts):

* `S` has no symbols;
* `M` has carrier `Bool`, no interpretations;
* `C := {true}`, which is nonempty, backward closed, and misses `star := false`;
* `ψ := ∀x. ∀y. (x → y)`, closed.

`⟦ψ⟧_M = ⋂_{a,b} ({a}ᶜ ∪ {b})`, and taking `a := true, b := false` shows
`true ∉ ⟦ψ⟧_M`, so `C ⊄ ⟦ψ⟧_M`.  But `↥C` is a singleton, so in the single
sheet only `a = b` is available and `⟦ψ⟧_{single} = univ`, i.e. `single ⊨ ψ`.
The two sides of Corollary 12 therefore disagree.

The double cover has carrier `↥C × Bool`, which has TWO elements, and so agrees
with `M` here -- see `cover_disagrees_with_single` at the end of this file. -/

namespace Refutation

/-- The empty signature: no symbols, hence no backward steps at all. -/
abbrev Sig : Signature where
  Sym := Empty
  arity := fun e => e.elim

/-- The two-element model over the empty signature. -/
abbrev M2 : Model Sig where
  carrier := Bool
  nonempty := ⟨true⟩
  interp := fun e => e.elim

/-- The one-element backward-closed set. -/
def C2 : Set M2.carrier := {true}

theorem C2_bc : M2.BackwardClosed C2 := by
  rintro u _ v ⟨e, _, _, _, _⟩
  exact e.elim

theorem C2_ne : C2.Nonempty := ⟨true, rfl⟩

theorem star_notin : (false : M2.carrier) ∉ C2 := by
  intro h
  exact Bool.noConfusion (h : (false : Bool) = true)

/-- Any valuation into `M`; `ψ` is closed, so the choice is immaterial. -/
def rho2 : Nat → M2.carrier := fun _ => true

/-- `∀x. ∀y. (x → y)`: "the carrier has at most one element". -/
def psi : Pattern Sig Nat :=
  Pattern.al 0 (Pattern.al 1 (Pattern.imp (Pattern.var 0) (Pattern.var 1)))

theorem psi_closed : Closed psi := by
  apply Set.eq_empty_iff_forall_notMem.mpr
  intro x hx
  simp only [psi, Pattern.al, Pattern.nt, FV_imp, FV_ex, FV_bot, FV_var,
    Set.union_empty, Set.mem_sdiff, Set.mem_union, Set.mem_singleton_iff] at hx
  tauto

/-- The carrier of the single sheet is a singleton. -/
theorem single_subsingleton (a b : (single M2 C2 C2_ne).carrier) : a = b := by
  apply Subtype.ext
  have ha := a.property
  have hb := b.property
  simp only [C2] at ha hb
  rw [ha, hb]

/-- The single sheet satisfies `ψ`: with only one element to range over, `∀x∀y`
never separates `x` from `y`. -/
theorem single_sat : (single M2 C2 C2_ne).Sat psi := by
  intro ν
  show _ = Set.univ
  apply Set.eq_univ_iff_forall.mpr
  intro u
  rw [psi, denote_al, Set.mem_iInter]
  intro a
  rw [denote_al, Set.mem_iInter]
  intro b
  rw [denote_imp]
  apply Set.mem_union_right
  rw [denote_var]
  exact single_subsingleton u _

/-- `M` refutes `ψ` already at `true ∈ C`: it has two elements. -/
theorem not_subset : ¬ (C2 ⊆ M2.denote rho2 psi) := by
  intro hsub
  have h1 := @hsub true rfl
  rw [psi, denote_al] at h1
  have h2 := Set.mem_iInter.mp h1 true
  rw [denote_al] at h2
  have h3 := Set.mem_iInter.mp h2 false
  rw [denote_imp, denote_var, denote_var] at h3
  have e0 : Function.update (Function.update rho2 0 true) 1 false 0 = true := by
    simp
  have e1 : Function.update (Function.update rho2 0 true) 1 false 1 = false := by
    simp
  rw [e0, e1] at h3
  rcases h3 with h3 | h3
  · exact h3 rfl
  · exact Bool.noConfusion h3

end Refutation

theorem v5_holds : V5Claim := by sorry

theorem v5_fails : ¬ V5Claim := by
  intro h
  have hiff := h Refutation.Sig Nat inferInstance Refutation.M2 Refutation.C2
    Refutation.C2_bc Refutation.C2_ne false Refutation.star_notin
    Refutation.psi Refutation.psi_closed Refutation.rho2
  exact Refutation.not_subset (hiff.mp Refutation.single_sat)

/-! ### What the second sheet does at the same data (not required)

`cover M2 C2` has carrier `↥C2 × Bool`, which has two elements, so it does NOT
satisfy `ψ` -- it agrees with `M` on the closed pattern, which is exactly what
Corollary 12 asserts and what the single sheet gets wrong. -/

theorem cover_disagrees_with_single :
    ¬ (cover Refutation.M2 Refutation.C2 Refutation.C2_ne).Sat Refutation.psi ∧
      (single Refutation.M2 Refutation.C2 Refutation.C2_ne).Sat Refutation.psi := by
  refine ⟨?_, Refutation.single_sat⟩
  intro hsat
  exact Refutation.not_subset
    ((cover_sat_iff Refutation.M2 Refutation.C2 Refutation.C2_bc Refutation.C2_ne
      false Refutation.star_notin Refutation.psi_closed Refutation.rho2).mp hsat)

end VariantSingleSheet
end MatchingLogic
